In [2]:
import pandas as pd

PROCESSED_DATA: str = "../data/processed"

In [3]:
df = pd.read_csv(f"{PROCESSED_DATA}/dataset.csv")
df["FECHA_OCURRENCIA"] = pd.to_datetime(df["FECHA_OCURRENCIA"])

# Agregando los días, meses y años por aparte
months = df["FECHA_OCURRENCIA"].dt.month
years = df["FECHA_OCURRENCIA"].dt.year
days = df["FECHA_OCURRENCIA"].dt.day

df["AÑO"] = years
df["DIA"] = days
df["MES"] = months

group_columns = [
    "AÑO",
    "DIA",
    "MES",
    "DIA_SEMANA_OCURRENCIA",
    "LOCALIDAD",
    "GRAVEDAD",
    "CLASE",
]

df

,OBJECTID,FORMULARIO,CODIGO_ACCIDENTE,FECHA_OCURRENCIA,DIA_SEMANA_OCURRENCIA,GRAVEDAD,CLASE,LOCALIDAD,latitude,longitude,AÑO,DIA,MES
0,646545,A00410124,306211,2008-09-05 12:50:00,5,CON HERIDOS,ATROPELLO,TEUSAQUILLO,4.655402,-74.101700,2008,5,9
1,563782,839933000,291565,2008-05-20 23:40:00,2,SOLO DANOS,CHOQUE,ENGATIVA,4.689417,-74.109351,2008,20,5
2,4398952,A000038718,4398952,2014-12-04 17:30:00,4,SOLO DANOS,CHOQUE,ENGATIVA,4.689750,-74.109016,2014,4,12
3,1612,726750500,30243,2007-06-29 19:30:00,5,CON HERIDOS,ATROPELLO,PUENTE ARANDA,4.615129,-74.108947,2007,29,6
4,569692,840564600,297475,2008-07-21 07:30:00,1,SOLO DANOS,CHOQUE,TEUSAQUILLO,4.646696,-74.108792,2008,21,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
329861,1707169,A00719849,352633,2010-03-04 14:30:00,4,SOLO DANOS,CHOQUE,FONTIBON,4.671688,-74.145705,2010,4,3
329862,9682,712264000,16686,2007-03-07 11:00:00,3,SOLO DANOS,CHOQUE,CIUDAD BOLIVAR,4.549462,-74.154415,2007,7,3
329863,4421360,A12506,4421360,2015-08-19 16:50:00,3,SOLO DANOS,CHOQUE,CIUDAD BOLIVAR,4.596006,-74.158040,2015,19,8
329864,60219,828721300,673,2008-01-05 19:27:00,6,SOLO DANOS,CHOQUE,TEUSAQUILLO,4.645298,-74.086861,2008,5,1
329865,3785505,A1392258,476909,2013-10-03 11:15:00,4,CON HERIDOS,ATROPELLO,KENNEDY,4.638998,-74.157927,2013,3,10

In [13]:
count = df.groupby(group_columns).count()[["OBJECTID"]]
result_df = count.reset_index()
result_df = result_df.rename(columns={"OBJECTID": "CANTIDAD"})
result_df

,AÑO,DIA,MES,DIA_SEMANA_OCURRENCIA,LOCALIDAD,GRAVEDAD,CLASE,CANTIDAD
0,2007,1,1,1,BOSA,CON HERIDOS,ATROPELLO,1
1,2007,1,1,1,BOSA,SOLO DANOS,CHOQUE,2
2,2007,1,1,1,CANDELARIA,SOLO DANOS,CHOQUE,1
3,2007,1,1,1,CHAPINERO,CON HERIDOS,CHOQUE,1
4,2007,1,1,1,CHAPINERO,CON HERIDOS,VOLCAMIENTO,1
...,...,...,...,...,...,...,...,...
138889,2017,31,8,4,TEUSAQUILLO,CON HERIDOS,CHOQUE,1
138890,2017,31,8,4,TEUSAQUILLO,SOLO DANOS,CHOQUE,5
138891,2017,31,8,4,USAQUEN,CON HERIDOS,CHOQUE,2
138892,2017,31,8,4,USAQUEN,SOLO DANOS,CHOQUE,7
138893,2017,31,8,4,USME,CON HERIDOS,CAIDA DE OCUPANTE,1

In [14]:
result_df.to_csv(f"{PROCESSED_DATA}/grouped.csv", index=False)